#!/usr/bin/env bash

# check to see if `jq` is installed
if !  $(hash jq) ;
then
    echo "$0: 'jq' is needed for JSON processing but it is not installed. Exiting!"
    exit 1
fi

# Get the API key from apikey.txt, located in the directory above the script
if ! [ -e ../apikey.txt ];
then
    echo "$0: Can't find the API key in '../apikey.txt'.  Exiting!"
    exit 1
else 
    APIKEY=$(head -1 ../apikey.txt)
fi

# Process each command line argument as a location
for location in "$@";
do
    # Make a request to http://api.openweathermap.org using the location as a query and imperial units
    # Capture the JSON response
    response=$(curl -s "http://api.openweathermap.org/data/2.5/weather?q=${location}&units=imperial&appid=${APIKEY}")
    # From the response, print the name of the location, the current temperature, and the main weather,
    name=$(echo $response | jq '.name')
    temp=$(echo $response | jq '.main.temp')
    main=$(echo $response | jq '.weather[0].main')
    echo "$name, $temp, $main"
done
