#!/usr/bin/env python
import requests

# Get the API key from apikey.txt, located in the directory above the script
# Process each command line argument as a location
# Make a request to http://api.openweathermap.org using the location as a query and imperial units
# Capture the JSON response
# From the response, print the name of the location, the current temperature, and the main weather,
