#!/usr/bin/env bash

APIKEY=$(head -1 ../apikey.txt)

for location in $@;
do
    response=$(curl -s "http://api.openweathermap.org/data/2.5/weather?q=${location}&units=imperial&appid=${APIKEY}")
    name=$(echo $response | jq '.name')
    temp=$(echo $response | jq '.main.temp')
    main=$(echo $response | jq '.weather[0].main')
    echo "$name, $temp, $main"
done

